# Tells Cloud Build: how to build the Docker image -> where to push it (Artifact Registry) -> to deploy on Cloud Run
steps:
  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f", "backend/Dockerfile",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA",
        ".",
      ]

  # Push image (so Cloud Run can pull it immediately)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA",
      ]

  # Deploy to Cloud Run + attach Cloud SQL + inject Secret
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",

        # Runtime service account
        "--service-account", "${_RUNTIME_SA}",

        # Attach cloud PostgreSQL instance
        "--add-cloudsql-instances", "${_CLOUDSQL_CONNECTION_NAME}",

        # Inject secret as env var (sets env vars DATABASE_URL + JWT_SECRET)
        "--set-secrets", "DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,REDIS_URL=REDIS_URL:latest,RESEND_API_KEY=RESEND_API_KEY:latest",

        # Non-secret runtime env (keeps production consistent across deploys)
        "--set-env-vars", "NODE_ENV=production,ENABLE_DEBUG_ROUTES=false,CORS_ORIGIN=https://career-tracker-frontend-ten.vercel.app,GCS_BUCKET=documents-career-tracker-482222,GCS_MAX_UPLOAD_BYTES=10485760,GCS_SIGNED_URL_TTL_SECONDS=600,GCS_ALLOWED_MIME_TYPES=application/pdf|text/plain,GCS_KEY_PREFIX=prod,OPENAI_MODEL=gpt-5-mini,OPENAI_MODEL_JD_EXTRACT=gpt-4o-mini,AI_DEBUG=true,EMAIL_FROM=cskash24@gmail.com,FRONTEND_URL=https://career-tracker-frontend-ten.vercel.app",

        # Quiet mode
        "--quiet"
      ]

# Kept for build metadata visibility in Cloud Build UI (tells Cloud Build: This build produced this image)
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"

# Custom variables
substitutions:
  # Registry info
  _REGION: "us-central1"
  _REPO: "career-tracker"
  _IMAGE: "career-tracker-api"

  # Cloud Run service name
  _SERVICE: "career-tracker-api"

  # Cloud Run runtime service account
  _RUNTIME_SA: "career-tracker-api@${PROJECT_ID}.iam.gserviceaccount.com"

  # Cloud SQL connection name
  _CLOUDSQL_CONNECTION_NAME: "${PROJECT_ID}:${_REGION}:career-tracker-db"

# Tell Cloud Build to send logs to Cloud Logging only (don’t store build logs in Cloud Storage bucket by default)
options:
  logging: CLOUD_LOGGING_ONLY